# Generated by Django 5.0.1 on 2024-02-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_signup_rename_name_patient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
